version: "3.9"
services:
  data:
    image: "postgres:12.3"
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: patients
    volumes:
      - ./data/patients.csv:/app/data/patients.csv
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
volumes:
  postgres-data:
